apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanzo-webhook
  namespace: hanzo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanzo-webhook
      release: hanzo
  template:
    metadata:
      labels:
        app: hanzo-webhook
        release: hanzo
    spec:
      serviceAccountName: hanzo-webhook
      containers:
        - name: hanzo-webhook
          image:  hanzoai/webhook:v4
          imagePullPolicy: Never
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "hanzo.ai"
            - name: SOLVER_NAME
              value: "hanzo"
            - name: DNS_API_URL
              value: ""
            - name: RELEASE_NUMBER
              value: "v1.0.0"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
      volumes:
        - name: certs
          secret:
            secretName: hanzo-webhook-webhook-tls
